model:
  device_map: auto
  trust_remote_code: true

generate:
  max_new_tokens: 256
  temperature: 0.7
  top_p: 0.9
  repetition_penalty: 1.05

data:
  test_file: data/R3_short_answer_exam_short.json
  n_examples: 5

outputs:
  dirname: outputs
  filename: generated_text01.jsonl

prompt: |-
  日本の法律に基づき、以下の設問に答えてください

  設問: {question}

  答え: 